In [ ]:
import torch
a = torch.tensor([[1, 2],
                  [3, 4]])
a.shape

torch.Size([2, 2])

In [20]:
import torch
a = torch.tensor([[1, 2],
                  [3, 4],
                  [3, 4]])
a = a
a.shape

torch.Size([3, 2])

In [ ]:
position_ids = torch.arange(10).expand(20, -1) # [batch_size, seq_len]
position_ids.shape
#position_ids.shape[0] [batch_size]

torch.Size([20, 10])

In [36]:
inv_freq = 1/ (10000 ** (torch.arange(0, 256, 2).float() / 256))
inv_freq.shape # dim/2
inv_freq_expanded = inv_freq[None, :, None].float()
inv_freq_expanded.shape # [1, dim/2, 1]
inv_freq_expanded = inv_freq_expanded.expand(position_ids.shape[0], -1, 1)
inv_freq_expanded.shape
# [batch_size, dim/2, 1]

torch.Size([20, 128, 1])

In [2]:
import torch
A = torch.randn(2, 3, 1)
B = torch.randn(2, 1, 4)
C = A @ B
C.shape


torch.Size([2, 3, 4])

In [27]:
x = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print("---x---")
print(x.shape)
print(x)
print(x.shape[-1] // 2)
x1 = x[..., : x.shape[-1] // 2]
print("---x1---")
print(x1.shape)
print(x1)
x2 = x[..., x.shape[-1] // 2 :]
print("---x2---")
print(x2.shape)
print(x2)

---x---
torch.Size([2, 4])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
2
---x1---
torch.Size([2, 2])
tensor([[1, 2],
        [5, 6]])
---x2---
torch.Size([2, 2])
tensor([[3, 4],
        [7, 8]])
